package Entity.app;
// Generated 07-03-2017 08:10:25 AM by Hibernate Tools 3.6.0


import java.math.BigDecimal;
import java.util.Date;

/**
 * TblServicioServicio generated by hbm2java
 */
public class TblServicioServicio  implements java.io.Serializable {


     private int tesIdServicioBi;
     private String tesTipoMovVc;
     private String tesCodigoViaVc;
     private String tesDetalleVc;
     private String tesCuentaVc;
     private String tesCuentaContableVc;
     private Integer tesCodigoSintesisBi;
     private BigDecimal tesComisionDc;
     private Boolean tesEstadoBt;
     private String tesUsuarioCreacionVc;
     private Date tesFechaCreacionDt;
     private String tesUsuarioModificacionVc;
     private Date tesFechaModificacionDt;
     private BigDecimal qrX;
     private BigDecimal qrY;
     private BigDecimal qrScale;
     private BigDecimal marginLeft;
     private BigDecimal marginRight;
     private BigDecimal marginTop;
     private BigDecimal marginBottom;
     private String delimitador;
     private Integer fontSize;

    public String getDireccion() {
        return direccion;
    }

    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
     private String direccion;

    public TblServicioServicio() {
    }

	
    public TblServicioServicio(int tesIdServicioBi) {
        this.tesIdServicioBi = tesIdServicioBi;
    }
    public TblServicioServicio(int tesIdServicioBi, String tesTipoMovVc, String tesCodigoViaVc, String tesDetalleVc, String tesCuentaVc, String tesCuentaContableVc, Integer tesCodigoSintesisBi, BigDecimal tesComisionDc, Boolean tesEstadoBt, String tesUsuarioCreacionVc, Date tesFechaCreacionDt, String tesUsuarioModificacionVc, Date tesFechaModificacionDt, BigDecimal qrX, BigDecimal qrY, BigDecimal qrScale, BigDecimal marginLeft, BigDecimal marginRight, BigDecimal marginTop, BigDecimal marginBottom, String delimitador, Integer fontSize) {
       this.tesIdServicioBi = tesIdServicioBi;
       this.tesTipoMovVc = tesTipoMovVc;
       this.tesCodigoViaVc = tesCodigoViaVc;
       this.tesDetalleVc = tesDetalleVc;
       this.tesCuentaVc = tesCuentaVc;
       this.tesCuentaContableVc = tesCuentaContableVc;
       this.tesCodigoSintesisBi = tesCodigoSintesisBi;
       this.tesComisionDc = tesComisionDc;
       this.tesEstadoBt = tesEstadoBt;
       this.tesUsuarioCreacionVc = tesUsuarioCreacionVc;
       this.tesFechaCreacionDt = tesFechaCreacionDt;
       this.tesUsuarioModificacionVc = tesUsuarioModificacionVc;
       this.tesFechaModificacionDt = tesFechaModificacionDt;
       this.qrX = qrX;
       this.qrY = qrY;
       this.qrScale = qrScale;
       this.marginLeft = marginLeft;
       this.marginRight = marginRight;
       this.marginTop = marginTop;
       this.marginBottom = marginBottom;
       this.delimitador = delimitador;
       this.fontSize = fontSize;
    }
   
    public int getTesIdServicioBi() {
        return this.tesIdServicioBi;
    }
    
    public void setTesIdServicioBi(int tesIdServicioBi) {
        this.tesIdServicioBi = tesIdServicioBi;
    }
    public String getTesTipoMovVc() {
        return this.tesTipoMovVc;
    }
    
    public void setTesTipoMovVc(String tesTipoMovVc) {
        this.tesTipoMovVc = tesTipoMovVc;
    }
    public String getTesCodigoViaVc() {
        return this.tesCodigoViaVc;
    }
    
    public void setTesCodigoViaVc(String tesCodigoViaVc) {
        this.tesCodigoViaVc = tesCodigoViaVc;
    }
    public String getTesDetalleVc() {
        return this.tesDetalleVc;
    }
    
    public void setTesDetalleVc(String tesDetalleVc) {
        this.tesDetalleVc = tesDetalleVc;
    }
    public String getTesCuentaVc() {
        return this.tesCuentaVc;
    }
    
    public void setTesCuentaVc(String tesCuentaVc) {
        this.tesCuentaVc = tesCuentaVc;
    }
    public String getTesCuentaContableVc() {
        return this.tesCuentaContableVc;
    }
    
    public void setTesCuentaContableVc(String tesCuentaContableVc) {
        this.tesCuentaContableVc = tesCuentaContableVc;
    }
    public Integer getTesCodigoSintesisBi() {
        return this.tesCodigoSintesisBi;
    }
    
    public void setTesCodigoSintesisBi(Integer tesCodigoSintesisBi) {
        this.tesCodigoSintesisBi = tesCodigoSintesisBi;
    }
    public BigDecimal getTesComisionDc() {
        return this.tesComisionDc;
    }
    
    public void setTesComisionDc(BigDecimal tesComisionDc) {
        this.tesComisionDc = tesComisionDc;
    }
    public Boolean getTesEstadoBt() {
        return this.tesEstadoBt;
    }
    
    public void setTesEstadoBt(Boolean tesEstadoBt) {
        this.tesEstadoBt = tesEstadoBt;
    }
    public String getTesUsuarioCreacionVc() {
        return this.tesUsuarioCreacionVc;
    }
    
    public void setTesUsuarioCreacionVc(String tesUsuarioCreacionVc) {
        this.tesUsuarioCreacionVc = tesUsuarioCreacionVc;
    }
    public Date getTesFechaCreacionDt() {
        return this.tesFechaCreacionDt;
    }
    
    public void setTesFechaCreacionDt(Date tesFechaCreacionDt) {
        this.tesFechaCreacionDt = tesFechaCreacionDt;
    }
    public String getTesUsuarioModificacionVc() {
        return this.tesUsuarioModificacionVc;
    }
    
    public void setTesUsuarioModificacionVc(String tesUsuarioModificacionVc) {
        this.tesUsuarioModificacionVc = tesUsuarioModificacionVc;
    }
    public Date getTesFechaModificacionDt() {
        return this.tesFechaModificacionDt;
    }
    
    public void setTesFechaModificacionDt(Date tesFechaModificacionDt) {
        this.tesFechaModificacionDt = tesFechaModificacionDt;
    }
    public BigDecimal getQrX() {
        return this.qrX;
    }
    
    public void setQrX(BigDecimal qrX) {
        this.qrX = qrX;
    }
    public BigDecimal getQrY() {
        return this.qrY;
    }
    
    public void setQrY(BigDecimal qrY) {
        this.qrY = qrY;
    }
    public BigDecimal getQrScale() {
        return this.qrScale;
    }
    
    public void setQrScale(BigDecimal qrScale) {
        this.qrScale = qrScale;
    }
    public BigDecimal getMarginLeft() {
        return this.marginLeft;
    }
    
    public void setMarginLeft(BigDecimal marginLeft) {
        this.marginLeft = marginLeft;
    }
    public BigDecimal getMarginRight() {
        return this.marginRight;
    }
    
    public void setMarginRight(BigDecimal marginRight) {
        this.marginRight = marginRight;
    }
    public BigDecimal getMarginTop() {
        return this.marginTop;
    }
    
    public void setMarginTop(BigDecimal marginTop) {
        this.marginTop = marginTop;
    }
    public BigDecimal getMarginBottom() {
        return this.marginBottom;
    }
    
    public void setMarginBottom(BigDecimal marginBottom) {
        this.marginBottom = marginBottom;
    }
    public String getDelimitador() {
        return this.delimitador;
    }
    
    public void setDelimitador(String delimitador) {
        this.delimitador = delimitador;
    }
    public Integer getFontSize() {
        return this.fontSize;
    }
    
    public void setFontSize(Integer fontSize) {
        this.fontSize = fontSize;
    }




}


