package Entity.app;
// Generated 12-03-2017 07:10:22 PM by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * TblServicioFactura generated by hbm2java
 */
public class TblServicioFactura  implements java.io.Serializable {


     private int tesIdFacturaBi;
     private Integer tesCodigoSintesisBi;
     private String tesOperacionVc;
     private String tesNitVc;
     private String tesNombreVc;
     private String tesCuentaVc;
     private String tesFacturaTexto;
     private String tesPagoRequest;
     private String tesPagoResponse;
     private Boolean tesEstadoBt;
     private String tesUsuarioCreacionVc;
     private Date tesFechaCreacionDt;
     private String tesUsuarioModificacionVc;
     private Date tesFechaModificacionDt;
     private Integer testIdDireccionBi;
     private Boolean print;
     private String userPrint;
     private Date datePrint;
     private String Servicio;
     private String Direccion;

    public String getServicio() {
        return Servicio;
    }

    public void setServicio(String Servicio) {
        this.Servicio = Servicio;
    }

    public String getDireccion() {
        return Direccion;
    }

    public void setDireccion(String Direccion) {
        this.Direccion = Direccion;
    }
     
    public TblServicioFactura() {
    }

	
    public TblServicioFactura(int tesIdFacturaBi) {
        this.tesIdFacturaBi = tesIdFacturaBi;
    }
    public TblServicioFactura(int tesIdFacturaBi, Integer tesCodigoSintesisBi, String tesOperacionVc, String tesNitVc, String tesNombreVc, String tesCuentaVc, String tesFacturaTexto, String tesPagoRequest, String tesPagoResponse, Boolean tesEstadoBt, String tesUsuarioCreacionVc, Date tesFechaCreacionDt, String tesUsuarioModificacionVc, Date tesFechaModificacionDt, Integer testIdDireccionBi, Boolean print, String userPrint, Date datePrint) {
       this.tesIdFacturaBi = tesIdFacturaBi;
       this.tesCodigoSintesisBi = tesCodigoSintesisBi;
       this.tesOperacionVc = tesOperacionVc;
       this.tesNitVc = tesNitVc;
       this.tesNombreVc = tesNombreVc;
       this.tesCuentaVc = tesCuentaVc;
       this.tesFacturaTexto = tesFacturaTexto;
       this.tesPagoRequest = tesPagoRequest;
       this.tesPagoResponse = tesPagoResponse;
       this.tesEstadoBt = tesEstadoBt;
       this.tesUsuarioCreacionVc = tesUsuarioCreacionVc;
       this.tesFechaCreacionDt = tesFechaCreacionDt;
       this.tesUsuarioModificacionVc = tesUsuarioModificacionVc;
       this.tesFechaModificacionDt = tesFechaModificacionDt;
       this.testIdDireccionBi = testIdDireccionBi;
       this.print = print;
       this.userPrint = userPrint;
       this.datePrint = datePrint;
    }
   
    public int getTesIdFacturaBi() {
        return this.tesIdFacturaBi;
    }
    
    public void setTesIdFacturaBi(int tesIdFacturaBi) {
        this.tesIdFacturaBi = tesIdFacturaBi;
    }
    public Integer getTesCodigoSintesisBi() {
        return this.tesCodigoSintesisBi;
    }
    
    public void setTesCodigoSintesisBi(Integer tesCodigoSintesisBi) {
        this.tesCodigoSintesisBi = tesCodigoSintesisBi;
    }
    public String getTesOperacionVc() {
        return this.tesOperacionVc;
    }
    
    public void setTesOperacionVc(String tesOperacionVc) {
        this.tesOperacionVc = tesOperacionVc;
    }
    public String getTesNitVc() {
        return this.tesNitVc;
    }
    
    public void setTesNitVc(String tesNitVc) {
        this.tesNitVc = tesNitVc;
    }
    public String getTesNombreVc() {
        return this.tesNombreVc;
    }
    
    public void setTesNombreVc(String tesNombreVc) {
        this.tesNombreVc = tesNombreVc;
    }
    public String getTesCuentaVc() {
        return this.tesCuentaVc;
    }
    
    public void setTesCuentaVc(String tesCuentaVc) {
        this.tesCuentaVc = tesCuentaVc;
    }
    public String getTesFacturaTexto() {
        return this.tesFacturaTexto;
    }
    
    public void setTesFacturaTexto(String tesFacturaTexto) {
        this.tesFacturaTexto = tesFacturaTexto;
    }
    public String getTesPagoRequest() {
        return this.tesPagoRequest;
    }
    
    public void setTesPagoRequest(String tesPagoRequest) {
        this.tesPagoRequest = tesPagoRequest;
    }
    public String getTesPagoResponse() {
        return this.tesPagoResponse;
    }
    
    public void setTesPagoResponse(String tesPagoResponse) {
        this.tesPagoResponse = tesPagoResponse;
    }
    public Boolean getTesEstadoBt() {
        return this.tesEstadoBt;
    }
    
    public void setTesEstadoBt(Boolean tesEstadoBt) {
        this.tesEstadoBt = tesEstadoBt;
    }
    public String getTesUsuarioCreacionVc() {
        return this.tesUsuarioCreacionVc;
    }
    
    public void setTesUsuarioCreacionVc(String tesUsuarioCreacionVc) {
        this.tesUsuarioCreacionVc = tesUsuarioCreacionVc;
    }
    public Date getTesFechaCreacionDt() {
        return this.tesFechaCreacionDt;
    }
    
    public void setTesFechaCreacionDt(Date tesFechaCreacionDt) {
        this.tesFechaCreacionDt = tesFechaCreacionDt;
    }
    public String getTesUsuarioModificacionVc() {
        return this.tesUsuarioModificacionVc;
    }
    
    public void setTesUsuarioModificacionVc(String tesUsuarioModificacionVc) {
        this.tesUsuarioModificacionVc = tesUsuarioModificacionVc;
    }
    public Date getTesFechaModificacionDt() {
        return this.tesFechaModificacionDt;
    }
    
    public void setTesFechaModificacionDt(Date tesFechaModificacionDt) {
        this.tesFechaModificacionDt = tesFechaModificacionDt;
    }
    public Integer getTestIdDireccionBi() {
        return this.testIdDireccionBi;
    }
    
    public void setTestIdDireccionBi(Integer testIdDireccionBi) {
        this.testIdDireccionBi = testIdDireccionBi;
    }
    public Boolean getPrint() {
        return this.print;
    }
    
    public void setPrint(Boolean print) {
        this.print = print;
    }
    public String getUserPrint() {
        return this.userPrint;
    }
    
    public void setUserPrint(String userPrint) {
        this.userPrint = userPrint;
    }
    public Date getDatePrint() {
        return this.datePrint;
    }
    
    public void setDatePrint(Date datePrint) {
        this.datePrint = datePrint;
    }




}


