package Entity.app;
// Generated 12-03-2017 07:10:22 PM by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * TblServicioDireccion generated by hbm2java
 */
public class TblServicioDireccion  implements java.io.Serializable {


     private int tesIdDireccionBi;
     private String tesTipoVc;
     private String tesCiudadVc;
     private String tesDireccionVc;
     private String tesDetalleVc;
     private Boolean tesEstadoBt;
     private String tesUsuarioCreacionVc;
     private Date tesFechaCreacionDt;
     private String tesUsuarioModificacionVc;
     private Date tesFechaModificacionDt;

    public TblServicioDireccion() {
    }

	
    public TblServicioDireccion(int tesIdDireccionBi) {
        this.tesIdDireccionBi = tesIdDireccionBi;
    }
    public TblServicioDireccion(int tesIdDireccionBi, String tesTipoVc, String tesCiudadVc, String tesDireccionVc, String tesDetalleVc, Boolean tesEstadoBt, String tesUsuarioCreacionVc, Date tesFechaCreacionDt, String tesUsuarioModificacionVc, Date tesFechaModificacionDt) {
       this.tesIdDireccionBi = tesIdDireccionBi;
       this.tesTipoVc = tesTipoVc;
       this.tesCiudadVc = tesCiudadVc;
       this.tesDireccionVc = tesDireccionVc;
       this.tesDetalleVc = tesDetalleVc;
       this.tesEstadoBt = tesEstadoBt;
       this.tesUsuarioCreacionVc = tesUsuarioCreacionVc;
       this.tesFechaCreacionDt = tesFechaCreacionDt;
       this.tesUsuarioModificacionVc = tesUsuarioModificacionVc;
       this.tesFechaModificacionDt = tesFechaModificacionDt;
    }
   
    public int getTesIdDireccionBi() {
        return this.tesIdDireccionBi;
    }
    
    public void setTesIdDireccionBi(int tesIdDireccionBi) {
        this.tesIdDireccionBi = tesIdDireccionBi;
    }
    public String getTesTipoVc() {
        return this.tesTipoVc;
    }
    
    public void setTesTipoVc(String tesTipoVc) {
        this.tesTipoVc = tesTipoVc;
    }
    public String getTesCiudadVc() {
        return this.tesCiudadVc;
    }
    
    public void setTesCiudadVc(String tesCiudadVc) {
        this.tesCiudadVc = tesCiudadVc;
    }
    public String getTesDireccionVc() {
        return this.tesDireccionVc;
    }
    
    public void setTesDireccionVc(String tesDireccionVc) {
        this.tesDireccionVc = tesDireccionVc;
    }
    public String getTesDetalleVc() {
        return this.tesDetalleVc;
    }
    
    public void setTesDetalleVc(String tesDetalleVc) {
        this.tesDetalleVc = tesDetalleVc;
    }
    public Boolean getTesEstadoBt() {
        return this.tesEstadoBt;
    }
    
    public void setTesEstadoBt(Boolean tesEstadoBt) {
        this.tesEstadoBt = tesEstadoBt;
    }
    public String getTesUsuarioCreacionVc() {
        return this.tesUsuarioCreacionVc;
    }
    
    public void setTesUsuarioCreacionVc(String tesUsuarioCreacionVc) {
        this.tesUsuarioCreacionVc = tesUsuarioCreacionVc;
    }
    public Date getTesFechaCreacionDt() {
        return this.tesFechaCreacionDt;
    }
    
    public void setTesFechaCreacionDt(Date tesFechaCreacionDt) {
        this.tesFechaCreacionDt = tesFechaCreacionDt;
    }
    public String getTesUsuarioModificacionVc() {
        return this.tesUsuarioModificacionVc;
    }
    
    public void setTesUsuarioModificacionVc(String tesUsuarioModificacionVc) {
        this.tesUsuarioModificacionVc = tesUsuarioModificacionVc;
    }
    public Date getTesFechaModificacionDt() {
        return this.tesFechaModificacionDt;
    }
    
    public void setTesFechaModificacionDt(Date tesFechaModificacionDt) {
        this.tesFechaModificacionDt = tesFechaModificacionDt;
    }




}


